# Generated by Django 3.2.4 on 2021-07-26 04:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='لطفا از زبان فارسی استفاده نمایید', regex='[ آابپتسجچحخدذرزسشصضطظعغفقکلمنوهی]+')], verbose_name='نام شهر')),
                ('city_population', models.PositiveBigIntegerField(verbose_name='جمعیت')),
                ('is_important', models.BooleanField(default=False, verbose_name='شهر اصلی است؟')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهر',
                'ordering': ['-city_population'],
            },
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('interviewer_code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='تعداد ارقام میبایست حداقل و حداکثر 5 رقم باشند', regex='^[0-9]{5}$')], verbose_name='کد پرسشگر')),
                ('interviewer_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='لطفا از زبان فارسی استفاده نمایید', regex='[ آابپتسجچحخدذرزسشصضطظعغفقکلمنوهی]+')], verbose_name='نام پرسشگر')),
            ],
            options={
                'verbose_name': 'پرسشگر',
                'verbose_name_plural': 'پرسشگر',
            },
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.IntegerField(choices=[(1, 'مجرد'), (2, 'متاهل'), (3, 'مطلقه'), (4, 'بیوه')], verbose_name='وضعیت تاهل')),
                ('age', models.IntegerField(choices=[(1, '24-18'), (2, '29-25'), (3, '34-30'), (4, '39-35')], verbose_name='بازه سنی')),
                ('maximum', models.PositiveSmallIntegerField(verbose_name='تعداد سهمیه')),
                ('capacity', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد ثبت نام شده')),
            ],
            options={
                'verbose_name': 'محدودیت',
                'verbose_name_plural': 'محدودیت',
                'ordering': ['marital_status', 'age'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.TextField(verbose_name='عنوان')),
                ('is_first', models.BooleanField(default=False, verbose_name='اولین پرسش است؟')),
                ('question_next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AgahSurvey.question', verbose_name='سوال بعدی')),
            ],
            options={
                'verbose_name': 'پرسش',
                'verbose_name_plural': 'پرسش',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_title', models.CharField(max_length=20, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'پرسشنامه',
                'verbose_name_plural': 'پرسشنامه',
            },
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='لطفا از زبان فارسی استفاده نمایید', regex='[ آابپتسجچحخدذرزسشصضطظعغفقکلمنوهی]+')], verbose_name='نام پاسخگو')),
                ('responser_family', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='لطفا از زبان فارسی استفاده نمایید', regex='[ آابپتسجچحخدذرزسشصضطظعغفقکلمنوهی]+')], verbose_name='نام خانوادگی پاسخگو')),
                ('responder_mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='لطفا شماره موبایل را به صورت کامل وارد نمایید', regex='^09[0-9]{9}$')], verbose_name='شماره موبایل')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AgahSurvey.city', verbose_name='نام شهر')),
            ],
            options={
                'verbose_name': 'پاسخگو',
                'verbose_name_plural': 'پاسخگو',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('region_value', models.PositiveSmallIntegerField(verbose_name='مقدار')),
                ('region_point', models.PositiveSmallIntegerField(verbose_name='امتیاز')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='AgahSurvey.city', verbose_name='شهر')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='AgahSurvey.question', verbose_name='پرسش')),
            ],
            options={
                'verbose_name': 'ناحیه',
                'verbose_name_plural': 'ناحیه',
                'ordering': ['city', '-region_point'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='AgahSurvey.survey', verbose_name='پرسشنامه'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_title', models.TextField(verbose_name='عنوان')),
                ('option_value', models.PositiveSmallIntegerField(verbose_name='مقدار')),
                ('option_point', models.PositiveSmallIntegerField(verbose_name='امتیاز')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='AgahSurvey.question', verbose_name='پرسش')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'گزینه',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_gender', models.CharField(choices=[('male', 'پسر'), ('female', 'دختر')], max_length=7, verbose_name='جنسیت')),
                ('child_birthday_year', models.IntegerField(validators=[django.core.validators.RegexValidator(message='لطفا سال تولد را صحیح و کامل وارد نمایید', regex='^1[0-9]{3}$')], verbose_name='سال تولد')),
                ('child_age', models.IntegerField(default=0, editable=False, verbose_name='محسابه سن اتومات')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='AgahSurvey.responder', verbose_name='پاسخگو')),
            ],
            options={
                'verbose_name': 'فرزند',
                'verbose_name_plural': 'فرزند',
                'ordering': ['-child_birthday_year'],
            },
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answersheet_date', models.DateField(verbose_name='تاریخ مصاحبه')),
                ('answersheet_day', models.CharField(max_length=20, verbose_name='روز هفته')),
                ('answersheet_total_point', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='مجموع امتیاز')),
                ('social_class', models.CharField(editable=False, max_length=1, verbose_name='کلاس اجتماعی')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AgahSurvey.interviewer', verbose_name='پرسشگر')),
                ('responser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgahSurvey.responder', verbose_name='پاسخگو')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgahSurvey.survey', verbose_name='پرسشنامه')),
            ],
            options={
                'verbose_name': 'پاسخنامه',
                'verbose_name_plural': 'پاسخنامه',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='پاسخ')),
                ('point', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='امتیاز')),
                ('answersheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='AgahSurvey.answersheet', verbose_name='پاسخنامه')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AgahSurvey.option', verbose_name='گزینه')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgahSurvey.question', verbose_name='پرسش')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ',
                'ordering': ['answersheet', 'question'],
            },
        ),
    ]
