# Generated by Django 3.2.4 on 2021-07-08 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgahSurvey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'پاسخ', 'verbose_name_plural': 'پاسخ'},
        ),
        migrations.AlterModelOptions(
            name='answersheet',
            options={'verbose_name': 'پاسخنامه', 'verbose_name_plural': 'پاسخنامه'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['-child_birthday_year'], 'verbose_name': 'فرزند', 'verbose_name_plural': 'فرزند'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-city_population'], 'verbose_name': 'شهر', 'verbose_name_plural': 'شهر'},
        ),
        migrations.AlterModelOptions(
            name='interviewer',
            options={'verbose_name': 'پرسشگر', 'verbose_name_plural': 'پرسشگر'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['pk'], 'verbose_name': 'گزینه', 'verbose_name_plural': 'گزینه'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pk'], 'verbose_name': 'پرسش', 'verbose_name_plural': 'پرسش'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['city', '-region_point'], 'verbose_name': 'ناحیه', 'verbose_name_plural': 'ناحیه'},
        ),
        migrations.AlterModelOptions(
            name='responder',
            options={'verbose_name': 'پاسخگو', 'verbose_name_plural': 'پاسخگو'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'پرسشنامه', 'verbose_name_plural': 'پرسشنامه'},
        ),
        migrations.AddField(
            model_name='answersheet',
            name='social_class',
            field=models.CharField(editable=False, max_length=1, verbose_name='کلاس اجتماعی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AgahSurvey.question', verbose_name='سوال بعدی'),
        ),
        migrations.AlterField(
            model_name='region',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='AgahSurvey.city', verbose_name='شهر'),
        ),
    ]
