# Generated by Django 3.2.4 on 2021-07-08 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgahSurvey', '0002_auto_20210708_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='AgahSurvey.question'),
        ),
    ]
