# Generated by Django 3.2.4 on 2021-07-10 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgahSurvey', '0003_alter_region_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام')),
                ('image', models.ImageField(upload_to='brand/', verbose_name='تصویر')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='AgahSurvey.question', verbose_name='پرسش')),
            ],
        ),
    ]
