# Generated by Django 3.2.4 on 2021-07-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgahSurvey', '0004_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brand/', verbose_name='تصویر'),
        ),
    ]
