# Generated by Django 3.2.4 on 2021-07-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgahSurvey', '0005_alter_brand_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برند'},
        ),
    ]
