# Generated by Django 3.2.4 on 2021-07-22 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgahSurvey', '0006_alter_brand_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgahSurvey.option', verbose_name='گزینه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(default=None, max_length=10, verbose_name='پاسخ'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
