# Generated by Django 3.2.4 on 2021-07-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgahSurvey', '0007_auto_20210722_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='پاسخ'),
        ),
    ]
