# Generated by Django 3.2.4 on 2021-07-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgahSurvey', '0010_answer_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='point',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='امتیاز'),
        ),
    ]
