# Generated by Django 3.2.4 on 2021-07-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgahSurvey', '0011_alter_answer_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.PositiveSmallIntegerField(verbose_name='کد وضعیت تاهل')),
                ('age', models.PositiveSmallIntegerField(verbose_name='کد بازه سنی')),
                ('maximum', models.PositiveSmallIntegerField(verbose_name='تعداد سهمیه')),
                ('capacity', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد ثبت نام شده')),
            ],
            options={
                'verbose_name': 'محدودیت',
                'verbose_name_plural': 'محدودیت',
            },
        ),
    ]
