# Generated by Django 3.2.4 on 2021-07-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgahSurvey', '0012_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='limit',
            options={'ordering': ['marital_status', 'age'], 'verbose_name': 'محدودیت', 'verbose_name_plural': 'محدودیت'},
        ),
        migrations.AlterField(
            model_name='limit',
            name='marital_status',
            field=models.PositiveSmallIntegerField(choices=[('مجرد', 1), ('متاهل', 2), ('مطلقه', 3), ('بیوه', 4)], verbose_name='وضعیت تاهل'),
        ),
    ]
