# Generated by Django 3.2.4 on 2021-07-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgahSurvey', '0013_auto_20210723_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='marital_status',
            field=models.IntegerField(choices=[('مجرد', 1), ('متاهل', 2), ('مطلقه', 3), ('بیوه', 4)], verbose_name='وضعیت تاهل'),
        ),
    ]
