# Generated by Django 3.2.4 on 2021-07-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgahSurvey', '0014_alter_limit_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='age',
            field=models.IntegerField(choices=[(1, '24-18'), (2, '29-25'), (3, '34-30'), (4, '39-35')], verbose_name='بازه سنی'),
        ),
        migrations.AlterField(
            model_name='limit',
            name='marital_status',
            field=models.IntegerField(choices=[(1, 'مجرد'), (2, 'متاهل'), (3, 'مطلقه'), (4, 'بیوه')], verbose_name='وضعیت تاهل'),
        ),
    ]
